name: Deploy to FTP

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: 🔨Build&test
      run: |
        npm install
        npm run build

    - name: 📦 Get LFTP
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: 🛠️ Configure LFTP
      run: mkdir -p ~/.lftp && echo "set ssl:verify-certificate false;" >> ~/.lftp/rc

    - name: 🔑 Load Secrets
      run: |
        printf 'machine %s login %s password %s\n' '${{ secrets.FTP_HOST }}' '${{ secrets.FTP_NAME }}' '${{ secrets.FTP_PASS }}' > ~/.netrc
        chmod 600 ~/.netrc

    - name: 📁 Upload Folder
      run: |
        echo "Upload to public_html/"
        lftp -d -e "set ftp:ssl-allow no; mirror --parallel=100 --only-newer --overwrite -R ./build/ /imsady6f.beget.tech/public_html/" ${{ secrets.FTP_HOST }}
